### ISSUE TITLE
keh keh ke lunga

### ISSUE THREAD

**Issue by srijitcoder** [IOSD/HackADGITM#2]
https://hackvsit.tech/  - Made With 💗 By [ACE](https://vipsace.org)

![whatsapp image 2019-02-22 at 9 33 06 pm](https://user-images.githubusercontent.com/10809211/53255213-2c4d7900-36eb-11e9-8078-6ccedf072bfa.jpeg)

**Comment by krishnarai30** [comment]
It was nice of you @srijitcoder to show such awesome OSS spirit. 
As IOSD we did love your designs and commend you for your skills but the spirit of work shown by you hasn't been up to the mark of OSS community.
We are replacing the code used by us, keeping in mind our telephonic conversation with you and your teammates, regarding you not allowing us to use your open source code in the spirit of creating an awesome hackathon.
All the best for your future endeavors.
